QUIZ_PLAN = {
    "Programming": 3,
    "Web Development": 3,
    "Networking": 3,
    "Cybersecurity": 4,
    "Hardware & Systems": 3,
    "General IT": 4,
}

QUESTIONS = [
    ("Programming", "What does DRY stand for in programming?",
     ["Don't Repeat Yourself", "Data Retrieval Yield", "Direct Run Yielding", "Define Reuse Yearly"], 0),
    ("Programming", "Which data structure follows the Last-In, First-Out (LIFO) rule?",
     ["Queue", "Stack", "Array", "Hash table"], 1),
    ("Programming", "What does len([1, 2, 3] + [4]) return in Python?",
     ["3", "5", "4", "It raises an error"], 2),
    ("Programming", "Which keyword defines a function in Python?",
     ["def", "func", "define", "fn"], 0),
    ("Programming", "What is the time complexity of binary search on a sorted array?",
     ["O(n)", "O(log n)", "O(n log n)", "O(1)"], 1),
    ("Programming", "What is recursion?",
     ["A loop that never ends", "A variable shared between functions", "A way to compile code", "A function that calls itself"], 3),
    ("Programming", "Which of these languages is dynamically typed by default?",
     ["Python", "C", "Java", "Rust"], 0),
    ("Programming", "What is the main purpose of a version control system like Git?",
     ["Compile code faster", "Track changes and collaborate on code", "Encrypt source files", "Host websites"], 1),

    ("Web Development", "Which HTML tag creates the largest heading?",
     ["<head>", "<h6>", "<h1>", "<title>"], 2),
    ("Web Development", "Which CSS property changes the color of text?",
     ["font-color", "color", "text-style", "foreground"], 1),
    ("Web Development", "What is CSS Flexbox mainly used for?",
     ["Querying databases", "Laying out items in a row or column", "Encrypting forms", "Compressing images"], 1),
    ("Web Development", "Which JavaScript keyword declares a block-scoped variable that cannot be reassigned?",
     ["var", "let", "const", "static"], 2),
    ("Web Development", "Which HTTP method is typically used to submit new data to a server?",
     ["GET", "POST", "HEAD", "TRACE"], 1),
    ("Web Development", "What does responsive design mean?",
     ["The site loads in under a second", "The layout adapts to different screen sizes", "The site uses only images", "The site works only offline"], 1),
    ("Web Development", "Which HTTP status code means the page was not found?",
     ["200", "301", "404", "500"], 2),
    ("Web Development", "What does the DOM represent?",
     ["A CSS framework", "A database model", "A server routing table", "The page structure as a tree of objects that JavaScript can change"], 3),

    ("Networking", "How many bits are in an IPv4 address?",
     ["16", "32", "64", "128"], 1),
    ("Networking", "Which device forwards packets between different networks?",
     ["Hub", "Switch", "Router", "Repeater"], 2),
    ("Networking", "What does DNS do?",
     ["Encrypts traffic", "Translates domain names into IP addresses", "Assigns MAC addresses", "Blocks malware"], 1),
    ("Networking", "Which protocol automatically assigns IP addresses to devices?",
     ["DHCP", "FTP", "SMTP", "ARP"], 0),
    ("Networking", "What is the default port for HTTPS?",
     ["80", "21", "443", "25"], 2),
    ("Networking", "Which subnet mask matches a /24 network?",
     ["255.0.0.0", "255.255.0.0", "255.255.255.0", "255.255.255.252"], 2),
    ("Networking", "At which OSI layer does a router primarily operate?",
     ["Layer 3 (Network)", "Layer 1 (Physical)", "Layer 2 (Data Link)", "Layer 7 (Application)"], 0),
    ("Networking", "What is the purpose of a VLAN?",
     ["Increase Wi-Fi speed", "Replace the need for routers", "Encrypt wired traffic", "Split a network into separate broadcast domains"], 3),

    ("Cybersecurity", "What is phishing?",
     ["A network speed test", "Tricking people into giving up sensitive information with fake messages", "A type of firewall", "A password manager feature"], 1),
    ("Cybersecurity", "What does a firewall do?",
     ["Cools server hardware", "Backs up data", "Filters network traffic based on rules", "Compresses files"], 2),
    ("Cybersecurity", "What does MFA stand for?",
     ["Multi-Factor Authentication", "Managed File Access", "Master Firewall Application", "Multiple Frame Allocation"], 0),
    ("Cybersecurity", "Which is the best password practice?",
     ["Reuse one long password everywhere", "Use your birthday plus a number", "Write it on a sticky note", "Use a unique passphrase for each account, stored in a password manager"], 3),
    ("Cybersecurity", "What is SQL injection?",
     ["Sending malicious SQL through unsanitized input to manipulate a database", "A way to speed up queries", "A database backup method", "A type of database index"], 0),
    ("Cybersecurity", "What does HTTPS provide that plain HTTP does not?",
     ["Faster page loading only", "Encrypted communication between browser and server", "Free hosting", "Automatic software updates"], 1),
    ("Cybersecurity", "Which is the best defense against ransomware?",
     ["Paying the ransom immediately", "Disabling the antivirus to avoid conflicts", "Regular offline backups and timely patching", "Ignoring software updates"], 2),
    ("Cybersecurity", "What is the principle of least privilege?",
     ["Users get only the access they need to do their job", "Everyone gets admin rights", "Passwords must be short", "Systems should run without logging"], 0),

    ("Hardware & Systems", "Which component is often called the brain of a computer?",
     ["RAM", "CPU", "PSU", "SSD"], 1),
    ("Hardware & Systems", "What is RAM used for?",
     ["Permanent file storage", "Cooling the CPU", "Connecting to the internet", "Short-term working memory for running programs"], 3),
    ("Hardware & Systems", "Which storage type has no moving parts?",
     ["HDD", "SSD", "Floppy disk", "Optical disc"], 1),
    ("Hardware & Systems", "What does the BIOS or UEFI do at startup?",
     ["Initializes hardware and starts the bootloader", "Installs applications", "Browses the web", "Compresses disk data"], 0),
    ("Hardware & Systems", "Which RAID level mirrors data across two drives?",
     ["RAID 0", "RAID 5", "RAID 1", "RAID 6"], 2),
    ("Hardware & Systems", "What does a PSU do?",
     ["Converts AC power into the DC power components need", "Stores user data", "Processes graphics", "Cools the case"], 0),
    ("Hardware & Systems", "Which Linux command lists the files in a directory?",
     ["cd", "rm", "ls", "chmod"], 2),
    ("Hardware & Systems", "What is virtualization?",
     ["Making a game look realistic", "Running multiple virtual machines on one physical machine", "Overclocking a CPU", "Encrypting a disk"], 1),

    ("General IT", "What does cloud computing mean?",
     ["Using weather data in apps", "Delivering computing services over the internet", "Storing data on floppy disks", "A type of Wi-Fi"], 1),
    ("General IT", "What does API stand for?",
     ["Application Programming Interface", "Automated Program Installer", "Applied Protocol Index", "Advanced Packet Inspection"], 0),
    ("General IT", "Which file extension is typically a compressed archive?",
     [".txt", ".png", ".zip", ".html"], 2),
    ("General IT", "What is the main job of an operating system?",
     ["Manage hardware and provide services for programs", "Browse the web", "Design graphics", "Write documents"], 0),
    ("General IT", "What does the 3-2-1 backup rule mean?",
     ["3 passwords, 2 users, 1 admin", "3 servers, 2 routers, 1 switch", "3 updates per week for 2 months", "3 copies of data on 2 types of media, with 1 copy offsite"], 3),
    ("General IT", "What is open-source software?",
     ["Software that is always free of bugs", "Software whose source code is available to view and modify under its license", "Software that only runs online", "Software without any license"], 1),
    ("General IT", "Which of these is a relational database?",
     ["MongoDB", "Redis", "PostgreSQL", "Neo4j"], 2),
    ("General IT", "What does troubleshooting best describe?",
     ["Replacing every part at once", "Always reinstalling the OS first", "Systematically finding and fixing the cause of a problem", "Ignoring error messages"], 2),
]
